# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Rollup Module

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 19.5.0
      uses: actions/setup-node@v1
      with:
        node-version: 19.5.0
    - run: rm scripts/gm-token-tools.min.js
    - run: npm ci
    - run: npm run build rollup.config.js --if-present
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Rollup Module'
        commit_options: '--no-verify --signoff'
        file_pattern: 'scripts/gm-token-tools.min.js'
        status_options: '--untracked-files=no'
        add_options: '-u'
        push_options: '--force'
        skip_dirty_check: true    
        skip_fetch: true
        skip_checkout: true
        disable_globbing: true
        create_branch: false